block.basepath: /data/fc_data/
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fch?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver